name: markdown-links

on:
  push:
    branches:
      - main
    paths:
      # filetypes
      - "**.md"
      - "**.rst"
      # self
      - ".github/workflows/markdown-link-check.yml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      # filetypes
      - "**.md"
      - "**.rst"
      # self
      - ".github/workflows/markdown-link-check.yml"

jobs:
  markdown-links-check:
    if: github.event.pull_request.draft == false
    name: Check markdown links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".mlc-config.json"
